-- MySQL Script generated by MySQL Workbench
-- Fri Aug  4 18:39:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema md_oferta_laboral
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema md_oferta_laboral
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `md_oferta_laboral` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `md_oferta_laboral` ;

-- -----------------------------------------------------
-- Table `md_oferta_laboral`.`tbl_ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `md_oferta_laboral`.`tbl_ubicacion` (
  `ubicacion_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ubicacion_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `md_oferta_laboral`.`tbl_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `md_oferta_laboral`.`tbl_empresa` (
  `empresa_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `ubicacion_id` INT(11) NOT NULL,
  PRIMARY KEY (`empresa_id`),
  CONSTRAINT `fk_tbl_empresa_tbl_ubicacion`
    FOREIGN KEY (`ubicacion_id`)
    REFERENCES `md_oferta_laboral`.`tbl_ubicacion` (`ubicacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `md_oferta_laboral`.`tbl_oferta_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `md_oferta_laboral`.`tbl_oferta_laboral` (
  `oferta_laboral_id` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `salario` DOUBLE NULL,
  `empresa_id` INT(11) NOT NULL,
  PRIMARY KEY (`oferta_laboral_id`),
  CONSTRAINT `fk_tbl_oferta_laboral_tbl_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `md_oferta_laboral`.`tbl_empresa` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `md_oferta_laboral`.`tbl_oferta_laboral_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `md_oferta_laboral`.`tbl_oferta_laboral_detalle` (
  `oferta_laboral_detalle_id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NULL,
  `url` VARCHAR(255) NOT NULL,
  `oferta_laboral_id` INT(11) NOT NULL,
  PRIMARY KEY (`oferta_laboral_detalle_id`),
  CONSTRAINT `fk_tbl_oferta_laboral_detalle_tbl_oferta_laboral1`
    FOREIGN KEY (`oferta_laboral_id`)
    REFERENCES `md_oferta_laboral`.`tbl_oferta_laboral` (`oferta_laboral_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `md_oferta_laboral`.`tbl_experencia_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `md_oferta_laboral`.`tbl_experencia_laboral` (
  `experencia_laboral_id` INT(11) NOT NULL AUTO_INCREMENT,
  `años_experencia` INT(2) NOT NULL,
  `oferta_laboral_id` INT(11) NOT NULL,
  PRIMARY KEY (`experencia_laboral_id`),
  CONSTRAINT `fk_tbl_experencia_laboral_tbl_oferta_laboral1`
    FOREIGN KEY (`oferta_laboral_id`)
    REFERENCES `md_oferta_laboral`.`tbl_oferta_laboral` (`oferta_laboral_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `md_oferta_laboral`.`tbl_modalidad_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `md_oferta_laboral`.`tbl_modalidad_laboral` (
  `modalidad_laboral_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `modalidad_laboral_id` INT(11) NOT NULL,
  PRIMARY KEY (`modalidad_laboral_id`),
  CONSTRAINT `fk_tbl_modalidad_laboral_tbl_oferta_laboral1`
    FOREIGN KEY (`modalidad_laboral_id`)
    REFERENCES `md_oferta_laboral`.`tbl_oferta_laboral` (`oferta_laboral_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
